export const PRIMARY = '#6D1F37'
export const PRIMARY_LIGHT = '#966473'
export const SECONDARY = '#C9B17B'
export const SECONDARY_LIGHT = '#CCB073'
export const WHITE = '#FFFFFF'
export const BLACK = '#000000'
export const LIGHT_GREY = '#dddddd'
export const WARM_GREY = '#7b7b7b'

export const SUCCESS = '#2f9725'
export const WARNING = '#ffae00'
export const DANGER = '#cc4b37'
export const DELETE = '#ff6a6a'
export const ERROR = '#a90007'

// GRAYSCALE
export const CARD_PRESSED = '#f5f5f5'
export const GRAY_LIGHT = '#e6e6e6'
export const GRAY_MEDIUM = '#E8F1F4'
export const GRAY_DARK = '#3D4C4E'
export const GRAY_DARK2 = '#767676'
export const MUTED = '#D5D5D5'
